### ISSUE TITLE
Diktat should run tests using SAVE-engine

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/diktat#1059]
We should rewrite our tests, so they would use `save` tests.

**Comment by petertrr** [comment]
Can it be considered done in #1060 ?

**Comment by Cheshiriks** [comment]
Not yet. Only one test is optimized for the fix and warn plugin.

**Comment by Cheshiriks** [comment]
> Can it be considered done in #1060 ?

Not yet. Only one test is optimized for the fix and warn plugin.

**Comment by akuleshov7** [comment]
Main logic is done and checked in warnings mode. We are blocked by ktlint release by for now.

**Comment by Cheshiriks** [comment]
completed in #1388
