### ISSUE TITLE
Do not wrap single statements in `run` in `AVOID_NULL_CHECKS` rule

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#1107]
```kotlin
foo() ?: run {
    bar()
}
```
should be just `foo() ?: bar()`

**Comment by akuleshov7** [comment]
I would say it's a bug

**Comment by kgevorkyan** [comment]
@petertrr Can't reproduce it with latest version of diktat
May be you have more concrete example?

**Comment by petertrr** [comment]
I suppose it was fixed in #899
