### ISSUE TITLE
Test Framework: Investigate failing tests Linux

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/diktat#1252]
Right now FIX tests are partially deleting test resources on Linux. Need to investigate that.

**Comment by akuleshov7** [comment]
may @nulls will investigate one day

**Comment by nulls** [comment]
The first candidate to reason of this issue is `org.cqfn.diktat.ruleset.generation.GenerationKt#validateYear`: it uses `java.io.File#renameTo` which looks like doesn't work on Unix system. Will migrate to `java.nio.file.Files#move`
