### ISSUE TITLE
Migrate to Gradle

### ISSUE THREAD

**Issue by nulls** [saveourtool/diktat#1301]
Use [save-cloud](https://github.com/saveourtool/save-cloud) project as reference

It's a stopper for
- #836
- #365

**Comment by akuleshov7** [comment]
It looks like when we will be migrating to Gradle - we will again create `/buildSrc` directory and that will be a duplication again. 
Probably it will be great to create a universal gradle plugin for Kotlin multiplatform plugin that will include main projects.
