### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by mre** [saveourtool/diktat#1303]
The link checker over at https://github.com/analysis-tools-dev/static-analysis/issues/1004 notified me that the website https://analysis-dev.github.io/diktat is not available at the moment. I wanted to let you know and wonder if you're planning to restore it. If not I would simply update the link to point to the Github repository.

**Comment by akuleshov7** [comment]
fixed - we moved to `diktat.saveourtool.com` domain. @0x6675636b796f75676974687562 could you please update awesome-kotlin and static-analysis-tools?

**Comment by mre** [comment]
Nice. Went ahead and change the static-analysis repo right away: https://github.com/analysis-tools-dev/static-analysis/commit/7528c519c897249962789d58954ced2652e06fae. It will take a minute until it gets reflected on our website at https://analysis-tools.dev/tool/diktat.

**Comment by 0x6675636b796f75676974687562** [comment]
@mre, many thanks for your contribution!
