### ISSUE TITLE
Implement ignoreAnnotated suppressor like detekt

### ISSUE THREAD

**Issue by WebTiger89** [saveourtool/diktat#1315]
There are a lot of false positive findings regarding **Jetpack Compose**. _Detekt_ handles this gently with a `ignoreAnnotated` suppressor. It's a List of Strings. Code that is annotated with an annotation of this list is ignored.

This would come really handy for following rules:
TOO_MANY_PARAMETERS
LAMBDA_IS_NOT_LAST_PARAMETER
TOO_LONG_FUNCTION
FUNCTION_NAME_INCORRECT_CASE
VARIABLE_NAME_INCORRECT_FORMAT
MISSING_KDOC_ON_FUNCTION

**Comment by akuleshov7** [comment]
@WebTiger89 `@Supress` annotation is not enough for this scenario?

**Comment by WebTiger89** [comment]
I guess no. This feature is really handy and it might be required for my last suggestion (https://github.com/saveourtool/diktat/issues/1322)

I can imagine that this requires a lot of work but it would improve every rule not only the ones mentioned above.

Just have a look into:
https://github.com/detekt/detekt/issues/4682

> To fix this I use, but it looks terrible and is bad practice `@SuppressWarnings("UnusedPrivateMember")`

https://detekt.dev/docs/introduction/suppressors/#annotation-suppressor
https://github.com/detekt/detekt/pull/4102

**Comment by akuleshov7** [comment]
I got it, yeah. Actually it is a quick fix for us

**Comment by akuleshov7** [comment]
We made even more: except the suppression of blocks that are marked with specific annotations, we also aded `@Suppress("diktat")` that will remove all inspections completely
