### ISSUE TITLE
False positive finding for NO_BRACES_IN_CONDITIONALS_AND_LOOPS rule on single line if statements

### ISSUE THREAD

**Issue by WebTiger89** [saveourtool/diktat#1318]
In config file is stated:

> Checks that braces are used in if, else, when, for, do, and while statements. Exception: single line if statement

but I get warnings for:
`if (isEmpty()) return -1` or `if (key == null || transformed == null) continue`

**Comment by akuleshov7** [comment]
By Single-line statements we mean “ternary” operator :) yes, should be updated in the description

**Comment by akuleshov7** [comment]
Yeah, even in our guide we meant “ternary”
https://github.com/saveourtool/diktat/blob/master/info/guide/diktat-coding-convention.md#-321-using-braces-in-conditional-statements-and-loop-blocks

**Comment by akuleshov7** [comment]
Btw: in case any of our inspections will be too strict for you - you can use `@Suppress(“ NO_BRACES_IN_CONDITIONALS_AND_LOOPS”)` annotation

**Comment by WebTiger89** [comment]
Yes I'm aware about it. Thanks for mentioning

**Comment by akuleshov7** [comment]
Updated docs in #1332

**Comment by WebTiger89** [comment]
@akuleshov7 Sorry, coming a bit late. The Kotlin style guide on android developer page (https://developer.android.com/kotlin/style-guide#formatting) encourages to write single line conditions like `if (isEmpty()) return -1 or if (key == null || transformed == null) continue`

You might consider to support this, maybe with a `true` `false` flag in the config for this rule to respect the origin intention. Unfortunately the official Kotlin guide does not mention how to handle single line conditions, see https://kotlinlang.org/docs/coding-conventions.html#conditional-statements
