### ISSUE TITLE
Fix only specific rules

### ISSUE THREAD

**Issue by WebTiger89** [saveourtool/diktat#1321]
I have checked the examples and the main page but I haven't found any configuration properties for the `diktatFix` task. Is it possible to fix only a specific rule, like TRAILING_COMMAS. If it's not available , it would be a really convenient feature.

**Comment by akuleshov7** [comment]
Nice enhancement for the future

**Comment by WebTiger89** [comment]
Is there some workaround I can use to just fix a specific rule or are you aware of another fast solution. I have hundreds of TRAILING_COMMA and WRONG_NEWLINES warnings but in between there are also warnings for other rules. It would be a bit cumbersome to disable the other rules temporarily. Any ideas?

**Comment by akuleshov7** [comment]
Unfortunately, you can do this only with a configuration file `diktat-analysis.yml`. All rules are enabled by the default, but you can simply mark them as `false` from `true` by one replacement in this file.

**Comment by WebTiger89** [comment]
Alright then I will go this way for now. Thanks

**Comment by akuleshov7** [comment]
https://github.com/saveourtool/diktat/issues/1274
Will be selective in the plugin for IDEA
