### ISSUE TITLE
Log lint errors even with `reporter=sarif`

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#1352]
Now (v 1.1.0) diktat-gradle-plugin doesn't log lint errors when reporter is set to SARIF. It makes it less obvious sometimes, e.g. when SARIF file failed to upload.

**Comment by petertrr** [comment]
Nope, we should simply use two reporters simultaneously: `reporter=plain,sarif`

**Comment by nulls** [comment]
supported:
- gradle and maven plugins supports two reporters now and plain is enabled by default.
- cli prints detected errors to stdout even when an additional reporter is configured
