### ISSUE TITLE
Inconsistency between ktlint and diktat in logging level when run from command line

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#1394]
The following applies to running ktlint+diktat in comand line:

ktlint executalbe jar bundles logback, but doesn't have any config file. Ktlint sets logging level programmatically, but only for a particular logger, that is used in `KtLintCommandLine.kt`. If neither of `--debug`, `--trace`, `--verbose` flags is present, it sets logback's level to `INFO`.

However, diktat uses multiple Slf4j loggers. Since no custom config for logback is present, the `BasicConfigurator` [is used](https://logback.qos.ch/manual/configuration.html) and logging level is set to `DEBUG`. This leads to several debug messages always showing up, see https://github.com/saveourtool/save-cli/issues/401#issuecomment-1161843347.

We should include a `logback.xml` into `diktat-ruleset` for setting default level to INFO, or try to find a way to share logging level with ktlint.

**Comment by nulls** [comment]
fixed by `KotlinLogging.loggerWithKtlintConfig`
also we have own cli now
