### ISSUE TITLE
Gradle plug-in: unable to specify inputs if Groovy DSL is used

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/diktat#1422]
Try to build the [example project](https://github.com/saveourtool/diktat/tree/master/examples/gradle-groovy-dsl) which uses the Groovy DSL. The build will fail:

```console
C:\diktat\examples\gradle-groovy-dsl>gradle build                                                                                                        
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\diktat\examples\gradle-groovy-dsl\build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'gradle-groovy-dsl'.
> No signature of method: build_8ip68wiz5ht9rnwfbccz91le2.diktat() is applicable for argument types: (build_8ip68wiz5ht9rnwfbccz91le2$_run_closure2) values: [build_8ip68wiz5ht9rnwfbccz91le2$_run_closure2@408bf572]
  Possible solutions: getAt(java.lang.String), with(groovy.lang.Closure), tap(groovy.lang.Closure)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

Apparently, the Groovy DSL doesn't understand this Kotlin signature:

```kotlin
    /**
     * Configure input files for diktat task
     *
     * @param action configuration lambda for `PatternFilterable`
     */
    fun inputs(action: PatternFilterable.() -> Unit) {
        action.invoke(patternSet)
    }
```

An empty `inputs { }` block is ok:

```groovy
diktat {
    inputs {
    }
    reporter = "plain"
    debug = false
}
```

Any attempt to specify the include or exclude rules within the block will lead to a failure.

## Environment information
* diktat version: 1.2.1
* build tool (maven/gradle): Gradle (6.8 and 7.4)
* how is diktat run (CLI, plugin, etc.): gradle plug-in
* kotlin version: 1.7.0
* operating system: Windows

**Comment by petertrr** [comment]
It can be used in Groovy with `it` parameter, for reasons described in [this answer](https://stackoverflow.com/questions/51140120/kotlin-function-parameter-with-receiver-called-from-groovy). We should update docs and check why our functional tests haven't captured this
