### ISSUE TITLE
Migrate to kotlin-logging

### ISSUE THREAD

**Issue by nulls** [saveourtool/diktat#1424]
Need to migrate to https://github.com/MicroUtils/kotlin-logging instead of usage SLF4J.

**Comment by akuleshov7** [comment]
Are you sure? Ktlint decided NOT to use Kotlin-logging

**Comment by petertrr** [comment]
@akuleshov7  ktlint does use kotlin-logging and we already started to use it in https://github.com/saveourtool/diktat/commit/43e6098c82ef9ed2de84e65775efb262cbfa79e3

**Comment by akuleshov7** [comment]
ah, nice! then what is this issue for?

**Comment by petertrr** [comment]
There is also an opened #1394 but I'm not sure which parts of these tasks are left. Need to reconsider it for the next minor release probably.
