### ISSUE TITLE
CONSTANT_UPPERCASE breaks the code.

### ISSUE THREAD

**Issue by Cheshiriks** [saveourtool/diktat#1425]
In fixed mode, this rule changes the constant to uppercase. But does not change these constants themselves in the code, thereby making the code not working

**Comment by sanyavertolet** [comment]
Isn't it wanted behavior?
Like we tell developer how it should be called and then he needs to correct it everywhere

**Comment by akuleshov7** [comment]
Exactly. We cannot do everything for the developer, especially in the case of renaming
