### ISSUE TITLE
Merging reports for GitHub Actions

### ISSUE THREAD

**Issue by CommanderTvis** [saveourtool/diktat#1435]
Is it possible to merge Diktat reports from Gradle subprojects in order to get a single SARIF file and upload it with GitHub Actions?

_Originally posted by @CommanderTvis in https://github.com/saveourtool/diktat/discussions/1434_

**Comment by akuleshov7** [comment]
We need to add readme example with Github Action for gradle and Maven. 

BUT THE BEST THING is finally to make a GitHub marketplace plugin

**Comment by CommanderTvis** [comment]
> BUT THE BEST THING is finally to make a GitHub marketplace plugin

No, it is not mandatory. Detekt is working fine without a custom GitHub action. With its Gradle plugin, a user can merge the SARIF reports from all projects into one file and upload it to GA.

**Comment by akuleshov7** [comment]
We have exactly the same, yeah - I've answered in the discussions

**Comment by akuleshov7** [comment]
https://github.com/saveourtool/diktat/issues/1216

**Comment by akuleshov7** [comment]
@CommanderTvis check this also: https://github.com/akuleshov7/reflekt/blob/master/.github/workflows/diktat.yml

**Comment by petertrr** [comment]
I didn't know, that detekt already has merging capabilities. Their `ReportMergeTask`, however, works for any SARIF files, which have common data and differ only in list of results. As a workaround, similarly to https://detekt.dev/docs/introduction/reporting/#kotlin-dsl `detekt-gradle-plugin` can be used to merge SARIF outputs of diktat.

**Comment by petertrr** [comment]
Implemented in befc9e96a8831ea6ddc40b2833db0c7e4fa012bc, d354d88ae742a37c3e1840f0a9531a11daf29703 and 2d754460d495faf8f72021f671db29457708b07c as a task `mergeDiktatReports` which is registered on the root project if any projects produce SARIF report from diktat plugin. Available in Diktat 1.2.3
