### ISSUE TITLE
New rule: there should not be overloading of methods that are overrides OR are abstract, especially when one of them is public and other one is private.

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/diktat#1526]
New rule: there should not be overloading of methods that are overrides OR are abstract, especially when one of them is public and other one is private.

_Originally posted by @akuleshov7 in https://github.com/saveourtool/diktat/pull/1520#discussion_r970878822_

## Related

 * #1593
 * #1594

**Comment by icemachined** [comment]
This seems to be incorrect rule, override is legal and may be necessary even in case of override overwise user will be able to call not overrided function from base class.
