### ISSUE TITLE
Upgrade `kaml`

### ISSUE THREAD

**Issue by nulls** [saveourtool/diktat#1540]
`kaml` uses `kotlinx.serialization` and it leads to dependency issue in ktlint running is due to  sarif4k.

So, the main problem is in `ktlint`:
```
     |    \--- io.github.detekt.sarif4k:sarif4k:0.0.1
     |         +--- org.jetbrains.kotlinx:kotlinx-serialization-json:1.1.0
     |         |    \--- org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.1.0
     |         |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.30 -> 1.7.20 (*)
     |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.30 -> 1.7.20
     |         |         \--- org.jetbrains.kotlinx:kotlinx-serialization-core:1.1.0
     |         |              \--- org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.1.0
     |         |                   +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.30 -> 1.7.20 (*)
     |         |                   \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.30 -> 1.7.20
```
It uses `https://github.com/detekt/sarif4k` which uses the old kotlinx serialization.
There is a PR to upgrade it: https://github.com/detekt/sarif4k/pull/4

After it, need to upgrade it in `ktlint`

_Originally posted by @nulls in https://github.com/saveourtool/diktat/issues/1518#issuecomment-1296764207_

**Comment by sanyavertolet** [comment]
@nulls Is this issue still relevant?

**Comment by nulls** [comment]
> @nulls Is this issue still relevant? Seems like `kotlinx.serialization` was updated in `detekt/safif4k` a long time ago

I don't know -- need to check dependencies

**Comment by nulls** [comment]
closed by shading `kotlinx.serialization` in https://github.com/saveourtool/diktat/pull/1654
