### ISSUE TITLE
"Configuration file not found in directory where diktat is run" warning is printed multiple times

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/diktat#1548]
For diktat running in console we print "Configuration file not found in directory where diktat is run" too many times, should be once. This issue can be duplicate. 

Affects usability of a cli tool.

**Comment by 0x6675636b796f75676974687562** [comment]
From the `RuleSetProvider` documentation (0.47.x):

> This method is going to be called once for each file (which means if any of the rules have state or
> are not thread-safe - a new `RuleSet` must be created).
> 
> This method is marked for removal in KtLint 0.48 for reason below:
> 
> For each invocation of `KtLint.lint` and `KtLint.format` the `RuleSet` is retrieved. This results in new
> instances of each `Rule` for each file being processed. As of that a `Rule` does not need to be thread-safe.
> 
> However, `KtLint.format` requires the `Rule` to be executed twice on o a file in case at least one violation
> has been autocorrected. As the same `Rule` instance is reused for the second execution of the `Rule`, the state
> of the `Rule` is shared. As of this `Rule` have to clear their internal state.

So now rules are expected to have a state, and a new `Rule` instance is created per a file checked.
