### ISSUE TITLE
Add main class for diktat.jar

### ISSUE THREAD

**Issue by nulls** [saveourtool/diktat#1557]
~~Produce additional artifact with required ktlint version.
It can be zip\tar.gz\tgz archive with final diktat fat jar and ktlint with proper version~~

Add main class for diktat which runs `KtLint.format` or `KtLint.lint`.
Need to support the same arguments as `Benedikt`

* [x] Add the main class (#1566 hasn't been cherry-picked into `master`).
* [x] `Main-Class` attribute in `META-INF/MANIFEST.MF` of the fat jar
* [x] ~~`Class-Path` attribute in `META-INF/MANIFEST.MF` of the fat jar~~

**Comment by 0x6675636b796f75676974687562** [comment]
Available since the [**1.2.4.2**](https://github.com/saveourtool/benedikt/releases/tag/v1.2.4.2) release of _Benedikt_.

What's missing, though, is _KtLint_ version resolution (currently, both _Diktat_ and _KtLint_ versions are hard-coded in the script)
