### ISSUE TITLE
Plugin not found error

### ISSUE THREAD

**Issue by ashtanko** [saveourtool/diktat#1876]
## Getting error when syncing up a gradle project:
Plugin [id: 'com.saveourtool.diktat.diktat-gradle-plugin', version: '1.2.5'] was not found in any of the following sources
the code:
``` kotlin
@Suppress("DSL_SCOPE_VIOLATION") // https://youtrack.jetbrains.com/issue/KTIJ-19369
plugins {
    id("com.saveourtool.diktat.diktat-gradle-plugin") version "1.2.5"
}

repositories {
    mavenCentral()
    maven { url = uri("https://repo.kotlin.link") }
    gradlePluginPortal()
    maven("https://plugins.gradle.org/m2/")
}
```
## Environment information
* diktat version:
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): plugin
* kotlin version: "1.9.21"   
* operating system: macOS 14.2
* link to a project (if your project is public):

**Comment by nulls** [comment]
hi @ashtanko,

We have changed group id and gradle id for plugin, but didn't change the documentation yet.

Can you please try the new version 2.0.0?

```kotlin
plugins {
    id("com.saveourtool.diktat") version "2.0.0"
}
```

**Comment by ashtanko** [comment]
> hi @ashtanko,
> 
> We have changed group id and gradle id for plugin, but didn't change the documentation yet.
> 
> Can you please try the new version 2.0.0?
> 
> ```kotlin
> plugins {
>     id("com.saveourtool.diktat") version "2.0.0"
> }
> ```

Hi @nulls, this variant is working, thanks for the clarification!
