### ISSUE TITLE
Enhancements for diktat-maven/gradle-plugin

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#365]
* [ ] fail-fast option (can it be done in maven at all?)
* [ ] goal for config generation (plugin writes default yml config to project base dir, gets domain name from maven's `groupId` or gradle's `project.groupId` or smth)
* [ ] choose ktlint reporter via plugin config:
  * [x]  #714 
  * [ ] support in maven
* [x] write tests for maven plugin (#543)
* ~in case of `RuleExecutionException` do not stop maven run~ - not needed?
* [ ] support gradle worker API, gradle incremental file changes (see ktlint-gradle as an example)

**Comment by nulls** [comment]
Not relevant after migration to Gradle
