### ISSUE TITLE
MULTIPLE_INIT_BLOCKS: fixer is too aggressive and can lead to a broken code

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/diktat#478]
Continuation of https://github.com/cqfn/diKTat/pull/459#discussion_r515816859
```
init { println(1) }

val a = "".also {  println(3) }
 
init { println(2) }
```

current fix will break the logic

**Comment by nulls** [comment]
checked on demo project -- doesn't break the code. looks like fixed together with #966
