### ISSUE TITLE
Diktat should either allow documentation of class fields in class KDoc via @property tag or have special error message for this case

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#788]
Now it's confusing: there is documentation, but not where diktat expects it, so it says that there is no documentation.

## Environment information
* diktat version: 0.4.1

**Comment by petertrr** [comment]
We should support permissive mode: if property is documented in class KDoc, then we shouldn't emit a warning. If there is no KDoc, we should suyggest to add it in clas body

**Comment by nulls** [comment]
already supported: we generates KDoc for constructors with generating `@param` and `@property`
