### ISSUE TITLE
Publish diktat-gradle-plugin to plugins.gradle.org

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#836]
Now users are required to add `mavenCentral` to plugin repositories, because gradle only searches gradle plugin portal by default

**Comment by akuleshov7** [comment]
Is plugins.gradle.org still alive? and mavenCentral is still not a default one?

**Comment by akuleshov7** [comment]
@petertrr

**Comment by nulls** [comment]
plugins.gradle.org is still alive and mavenCentral is not a default one.
There is instruction how to publish own plugin to gradle plugins, but it requires Gradle as a build system: https://plugins.gradle.org/docs/publish-plugin

Will be done after #1301

**Comment by nulls** [comment]
Created account on Gradle platfrom: saveourtool

**Comment by nulls** [comment]
we published a version under `saveourtool` account, but it was rejected, because need to proof that `saveourtool.com` belongs to us
