### ISSUE TITLE
Boolean conditions: support prefix negation

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#961]
Now we treat `!foo` as an elementary expression, i.e. we fix stuff like `!(foo && bar)` as `!(A & B)`, but treat `!foo && bar` as `A & B` instead of `!A & B`.
Also we can support negating equals operator: `!(x == null || y == null)` -> `x != null && y != null`

**Comment by akuleshov7** [comment]
Probably @nulls can help. (I hope so)
