### ISSUE TITLE
Illegal reflective operation warning from kotlin-compiler-embeddable

### ISSUE THREAD

**Issue by petertrr** [saveourtool/diktat#982]
I think under this issue we can also investigate problem with extra warnings from kotlin
Seems, it should be fixed ([youtrack](https://youtrack.jetbrains.com/issue/KT-43520), [stackoverflow](https://stackoverflow.com/questions/66977883/an-illegal-reflective-access-operation-has-occurred)) in `kotlin 1.5`

_Originally posted by @kgevorkyan in https://github.com/cqfn/diKTat/issues/971#issuecomment-877263916_

**Comment by akuleshov7** [comment]
All compilation warnings should be fixed under this issue

**Comment by petertrr** [comment]
@akuleshov7 we don't have any compilation warnings, because we've enabled `-Werror` long ago under #781 

This issue is about runtime warning which appears to be caused by incorrect usage of reflection deep inside kotlin-compiler. It needs some investigation, but it'll probably have to be resolved on their side.

**Comment by nulls** [comment]
Tested, it was fixed. Added a checking on `WARNING` in diktat cli output in tests
